### ISSUE TITLE
Add Summary Stats (e.g. Total Resources)

### ISSUE THREAD

**Issue by danieljrobles** [Yopiter/Resource-finder#2]
When searching for a resource, it is helpful to know how much is available.  This is especially true when playing Space Exploration where you need to travel to various planets to obtain various resources.

**Comment by Yopiter** [comment]
Not sure I understand your request here, the amount per patch is printed next to the location, and a sum/count of all patches does not seem that useful to me. Especially for SE where you usually explore the entire surface and end up with dozens of patches, many too small to be of interest. 
The idea behind the mod was to easily find relevant patches, since I usually don't bother connecting small patches anyway.
Please clarify what stats you were thinking of and what you would use them for.

**Comment by danieljrobles** [comment]
Yes the total is shown per patch, but I meant summary in total.  

For example:

```
1.2M Iron Ore X,Y
1.1M Iron Ore X,Y
0.7M Iron Ore X,Y
0.5M Iron Ore X,Y

3.5m Iron Ore Total on Planet Azure
``` 

_This is a pure nice to have feature enhancement :)_
